// Product catalog data — edit/add products here, no HTML editing needed.
// featured:true adds the gold highlight style to the card.
const PRODUCTS = [
                { id: 'beige-gold-evening-clutch', name: 'Beige Gold Evening Clutch', price: 189.99, category: 'Bags', image: 'photo-1548036328-c9fa89d128fa.jpg', featured: true },
                        { id: 'taupe-structured-top-handle-bag', name: 'Taupe Structured Top-Handle Bag', price: 259.99, category: 'Bags', image: 'taupe-structured-top-handle-bag.png', featured: true },
    { id: 'black-quilted-chain-shoulder-bag', name: 'Black Quilted Chain Shoulder Bag', price: 279.99, category: 'Bags', image: 'black-quilted-chain-shoulder-bag.png', featured: true },
    { id: 'aurora-solitaire-engagement-ring', name: 'Aurora Solitaire Engagement Ring', price: 349.99, category: 'Engagement Rings', image: 'photo-1605100804763-247f67b3557e.jpg', featured: true },
    { id: 'halo-diamond-engagement-ring', name: 'Halo Diamond Engagement Ring', price: 399.99, category: 'Engagement Rings', image: 'photo-1589674781759-c21c37956a44.jpg', featured: true },
            { id: 'classic-round-solitaire-engagement-ring', name: 'Classic Round Solitaire Engagement Ring', price: 379.99, category: 'Engagement Rings', image: 'classic-round-solitaire-engagement-ring.png', featured: true },
    { id: 'black-diamond-vintage-engagement-ring', name: 'Black Diamond Vintage Engagement Ring', price: 419.99, category: 'Engagement Rings', image: 'black-diamond-vintage-engagement-ring.png', featured: true },
    { id: 'rose-gold-oval-halo-engagement-ring', name: 'Rose Gold Oval Halo Engagement Ring', price: 449.99, category: 'Engagement Rings', image: 'rose-gold-oval-halo-engagement-ring.png', featured: true },
    { id: 'twist-band-diamond-engagement-ring', name: 'Twist Band Diamond Engagement Ring', price: 389.99, category: 'Engagement Rings', image: 'twist-band-diamond-engagement-ring.png', featured: true },
    { id: 'heart-cut-diamond-engagement-ring', name: 'Heart-Cut Diamond Engagement Ring', price: 409.99, category: 'Engagement Rings', image: 'heart-cut-diamond-engagement-ring.png', featured: true },
    { id: 'onyx-signet-statement-ring', name: 'Onyx Signet Statement Ring', price: 349.99, category: 'Engagement Rings', image: 'onyx-signet-statement-ring.png', featured: true },
    { id: 'imperial-gold-chain', name: 'Imperial Gold Chain', price: 139.99, category: 'Chains', image: 'photo-1611591437281-460bfbe1220a.jpg', featured: true },
    { id: 'box-link-gold-chain', name: 'Box Link Gold Chain', price: 149.99, category: 'Chains', image: 'photo-1602751584552-8ba73aad10e1.jpg', featured: true },
    { id: 'onyx-pendant-necklace', name: 'Onyx Pendant Necklace', price: 189.99, category: 'Necklaces', image: 'photo-1599643478518-a784e5dc4c8f.jpg', featured: true },
    { id: 'gold-clover-onyx-pendant-necklace', name: 'Gold Clover Onyx Pendant Necklace', price: 189.99, category: 'Necklaces', image: 'gold-clover-onyx-pendant-necklace.png', featured: true },
    { id: 'gold-wave-diamond-pendant-necklace', name: 'Gold Wave Diamond Pendant Necklace', price: 209.99, category: 'Necklaces', image: 'gold-wave-diamond-pendant-necklace.png', featured: true },
    { id: 'silver-diamond-leaf-pendant-necklace', name: 'Silver Diamond Leaf Pendant Necklace', price: 229.99, category: 'Necklaces', image: 'silver-diamond-leaf-pendant-necklace.png', featured: true },
        { id: 'gold-teardrop-diamond-pendant-necklace', name: 'Gold Teardrop Diamond Pendant Necklace', price: 199.99, category: 'Necklaces', image: 'gold-teardrop-diamond-pendant-necklace.png', featured: true },
    { id: 'black-onyx-station-pendant-necklace', name: 'Black Onyx Station Pendant Necklace', price: 219.99, category: 'Necklaces', image: 'black-onyx-station-pendant-necklace.png', featured: true },
    { id: 'celeste-diamond-drop-earrings', name: 'Celeste Diamond Drop Earrings', price: 119.99, category: 'Earrings', image: 'photo-1535632787350-4e68ef0ac584.jpg', featured: true },
    { id: 'gold-pearl-hoop-earrings', name: 'Gold Pearl Hoop Earrings', price: 94.99, category: 'Earrings', image: 'photo-1635767798638-3e25273a8236.jpg', featured: true },
    { id: 'black-onyx-stud-earrings', name: 'Black Onyx Stud Earrings', price: 89.99, category: 'Earrings', image: 'photo-1506630448388-4e683c67ddb0.jpg', featured: true },
    { id: 'diamond-pave-hoop-earrings', name: 'Diamond Pavé Hoop Earrings', price: 129.99, category: 'Earrings', image: 'diamond-pave-hoop-earrings.png', featured: true },
    { id: 'midnight-gold-watch', name: 'Midnight Gold Watch', price: 279.99, category: 'Watches', image: 'photo-1523170335258-f5ed11844a49.jpg', featured: true },
    { id: 'diamond-bezel-gold-watch', name: 'Diamond Bezel Gold Watch', price: 329.99, category: 'Watches', image: 'photo-1526045431048-f857369baa09.jpg', featured: true },
    { id: 'white-gold-steel-watch', name: 'White Gold Steel Watch', price: 299.99, category: 'Watches', image: 'photo-1434056886845-dac89ffe9b56.jpg', featured: true },
    { id: 'black-ceramic-gold-watch', name: 'Black Ceramic Gold Watch', price: 359.99, category: 'Watches', image: 'photo-1547996160-81dfa63595aa.jpg', featured: true },
];